--
-- File generated with SQLiteStudio v3.2.1 on Sun Nov 17 17:45:15 2019
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: Cooks
CREATE TABLE Cooks (CookId INTEGER PRIMARY KEY AUTOINCREMENT, Title nvarchar [256], CookStart TIMESTAMP NOT NULL, CookEnd TIMESTAMP, SmokerTarget DOUBLE, Target DOUBLE);

-- Table: ErrorLog
CREATE TABLE ErrorLog (ErroLogId INTEGER PRIMARY KEY AUTOINCREMENT, EventDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, Error TEXT NOT NULL);

-- Table: Sensors
CREATE TABLE Sensors (SensorId INTEGER PRIMARY KEY NOT NULL, SensorName STRING (255));

-- Table: TempLog
CREATE TABLE TempLog (TempLogId INTEGER PRIMARY KEY AUTOINCREMENT, EventDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP REFERENCES Sensors (SensorId), Temp1 FLOAT NOT NULL, Temp2 FLOAT NOT NULL, Temp3 FLOAT NOT NULL, CookId INTEGER REFERENCES Cooks (CookId));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
